---
dist: xenial
sudo: required

language: python

matrix:
  include:
    - python: 3.7
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: pypy
      env: TOXENV=pypy

install:
  - pip install tox-travis

script: tox
